{{- define "nexus-oidc-proxy.configMapContents" -}}
data:
  '{{ .Values.config.existingConfigMap.key }}': |-
    {{- .Values.config.yaml | toYaml | nindent 4 }}
{{- end -}}

{{- if not .Values.config.existingConfigMap.name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nexus-oidc-proxy.configMapName" . }}
  labels:
    {{ include "nexus-oidc-proxy.labels" . | nindent 4 }}
{{ include "nexus-oidc-proxy.configMapContents" . }}
{{- end }}
