name: CI

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch: {}
  push:
    # Tags should be built by CD instead
    tags-ignore: ['*']
    branches: ['*']
  pull_request: {}

env:

  GO_VERSION: 1.18

  GOPRIVATE: 'github.com/meln5674/*'

  HELM_VERSION: v3.12.0

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install deps
      - uses: actions/setup-go@v4
        with:
          go-version: '^${{ env.GO_VERSION }}'

      - name: Install Dependencies
        run: |
          make deps 

      # Run Linter
      - name: Lint
        run: |
          go vet

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install Deps

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: '${{ env.HELM_VERSION }}'
      
      - uses: actions/setup-go@v4
        with:
          go-version: '^${{ env.GO_VERSION }}'

      - name: Install Dependencies
        run: |
          make deps 

      # Tests
      # # TODO
      # - name: Unit Tests
      #   run: |
      #     make test
      - name: End-to-End Tests
        run: |
          make e2e
